#!/bin/bash
#
# License: CC0
#
# To the extent possible under law, the person who associated CC0 with
# this project has waived all copyright and related or neighboring rights
# to this project.
# 
# You should have received a copy of the CC0 legalcode along with this
# work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
#

export D=32
export M=1000

if [[ "$1" != "" ]] ; then
  export D="$1"
fi

mkdir -p data


gcc -O3 littlewoodp.c -o littlewoodp

for D in `seq 10 256` ; do
  echo "# $D"
  ./littlewoodp $D $M | xargs -n1 -I{} mpsolve -p '{}' | tr -d '(),' > data/lwp-d${D}_i${M}.gp
  cat data/lwp-d${D}_i${M}.gp | ./clog.py > data/ln_lwp-d${D}_i${M}.gp
done
