#!/bin/bash
#
#
# to test:
#
#  mkfifo encoder-pipe
#  exec 3>encoder-pipe
#  ../mode-manager/mode-manager  -L ./innerlight.led  <( ../mode-manager/rando-inp ) encoder-pipe
#  echo '12 0 2 0' >> encoder-pipe
#  ....
#  exec 3>&-
#
# Note that the first exec will hang until there is a reader on the pipe,
#

#../mode-manager/mode-manager  -L ./innerlight.led  <( ../mode-manager/rando-inp ) <( ./null-encoder )
#../mode-manager/mode-manager  -L ./innerlight.led  <( ../mode-manager/rando-inp ) <( ../mode-manager/rando-inp-encoder )
#../mode-manager/mode-manager  -L ./innerlight.led  <( ../mode-manager/rando-inp ) encoder-pipe

ledfn="/tmp/innerlight.led"
ledtest="/tmp/ledtest.txt"
cfgfn="/tmp/innerlight.ini"
pidfn="/tmp/inner-light-generator.pid"
imgdir="/tmp/img"

echo "../inner-light-generator/inner-light-generator -L $ledfn -T $ledtest -c $cfgfn -p $pidfn -I $imgdir <( ../mode-manager/rando-inp ) encoder-pipe"
../inner-light-generator/inner-light-generator -n 183 -L $ledfn -T $ledtest -c $cfgfn -p $pidfn -I $imgdir <( ../mode-manager/rando-inp ) encoder-pipe


#../inner-light-generator/inner-light-generator -L ./innerlight.led  -T ../../html/ledtest.txt <( ../mode-manager/rando-inp ) encoder-pipe
#valgrind ../inner-light-generator/inner-light-generator -L ./innerlight.led  -T ../../html/ledtest.txt <( ../mode-manager/rando-inp ) encoder-pipe 2> err

