#!/bin/bash

#../mode-manager/mode-manager  -L ./innerlight.led  <( ../mode-manager/rando-inp ) <( ./null-encoder )
../mode-manager/mode-manager  -L ./innerlight.led  <( ../mode-manager/rando-inp ) <( ../mode-manager/rando-inp-encoder )

