#!/bin/bash

./drills.sh

dx="0"
dy="-200"

#grecode -shift 0 -200 board-cuts.ngc > fin-cuts.ngc
grecode -shift "$dx" "$dy" board-cuts.ngc > fin-cuts.ngc

cat ../gcode/board-F_Cu.gtl | grbl_inch2mm.py > cu.ngc

#grecode -shift 0 -200 cu.ngc > fin-cu.ngc
grecode -shift "$dx" "$dy" cu.ngc > fin-cu.ngc

cat fin-cu.ngc fin-cuts.ngc > preview.ngc

