#!/bin/bash

./drills.sh

dx="-90"
dy="-130"

grecode -shift "$dx" "$dy" board-cuts.ngc > fin-cuts.ngc

cat ../gcode/board-F_Cu.gtl | grbl_inch2mm.py > cu.ngc

grecode -shift "$dx" "$dy" cu.ngc > fin-cu.ngc

cat fin-cu.ngc fin-cuts.ngc > preview.ngc

