#!/bin/bash
#
# License: cc0
#
# Meant to be run as root.
#

export CLIENT_SSID="$1"
export CLIENT_PASS="$2"
export AP_SSID="FlitterHaus"
export AP_PASS="cosmicdread"

# Install pre-requisite packages
#
apt-get install -y dnsmasq hostapd at

# Disable dhcpcd and other services
#
systemctl mask networking.service dhcpcd.service
systemctl unmask hostapd
#systemctl enable hostapd
#systemctl start hostapd

# add ap0 as access point interface
#
export wifimac=`cat /sys/class/net/wlan0/address`
cat > /etc/udev/rules.d/70-persistent-net.rules <<EOF
SUBSYSTEM=="ieee80211", ACTION=="add|change", ATTR{macaddress}=="$wifimac", KERNEL=="phy0", \
  RUN+="/sbin/iw phy phy0 interface add ap0 type __ap", \
  RUN+="/bin/ip link set ap0 address $wifimac"
EOF

# Setup access point config file
#
cat > /etc/hostapd/hostapd.conf <<EOF
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
interface=ap0
driver=nl80211
ssid=$AP_SSID
wpa_passphrase=$AP_PASS
hw_mode=g
channel=11
wmm_enabled=0
macaddr_acl=0
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
rsn_pairwise=CCMP
EOF

# Point hostapd to appropriate config file
#
sed -i 's;^#\?DAEMON_CONF=.*;DAEMON_CONF="/etc/hostapd/hostapd.conf";' /etc/default/hostapd

# Populate wpa_supplicant.conf (left commented out as this can be used as is if this is already set up)
# Note: the id_str="AP1" line is **necessary**.
#
#cat > /etc/wpa_supplicant/wpa_supplicant.conf <<EOF
#ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
#update_config=1
#country=US
#
#network={
#  ssid="$CLIENT_SSID"
#  psk="$CLIENT_PASS"
#  key_mgmt=WPA-PSK
#  id_str="AP1"
#}
#EOF

# setup DNS so connected devices through access point get an actual IP.
# Note that this overwrites /etc/dnsmasq.conf
#
cat > /etc/dnsmasq.conf <<EOF
interface=lo,ap0
no-dhcp-interface=lo,wlan0
bind-interfaces
server=8.8.8.8
domain-needed
bogus-priv
dhcp-range=192.168.10.50,192.168.10.150,12h
EOF

# Setup networking
#
cat > /etc/network/interfaces <<EOF
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

auto lo
auto ap0
auto wlan0
iface lo inet loopback

allow-hotplug ap0
iface ap0 inet static
    address 192.168.10.32
    netmask 255.255.255.0
    hostapd /etc/hostapd/hostapd.conf

allow-hotplug wlan0
iface wlan0 inet manual
    wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
iface AP1 inet dhcp
EOF

# There are problems with bringing up the interface so we have to do some trickery
# to wait a bit after reboot and then force them down and up again, as well
# as 'manually' add routing from the access point to the wider internet
#
cat > /home/pi/start-ap-managed-wifi.sh <<EOF
#!/bin/bash
sleep 30
sudo ifdown --force wlan0 && \
  sudo ifdown --force ap0 && \
  sudo ifup ap0 && \
  sudo ifup wlan0
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -s 192.168.10.0/24 ! -d 192.168.10.0/24 -j MASQUERADE
sudo systemctl restart dnsmasq
EOF

chown pi:pi /home/pi/start-ap-managed-wifi.sh
chmod 744 /home/pi/start-ap-managed-wifi.sh

cat > /home/pi/crontab <<EOF
@reboot /home/pi/start-ap-managed-wifi.sh
EOF

chown pi:pi /home/pi/crontab
chmod 744 /home/pi/crontab

#su - pi bash -c "crontab < /home/pi/crontab"


