
OPT=-std=gnu++11
INC=-I/usr/local/include/opencv4
LIB=-lopencv_aruco -L/usr/local/lib -lopencv_core -lopencv_imgcodecs

aruco-test: aruco-test.cpp
	g++ ${OPT} -lm ${INC} aruco-test.cpp -o aruco-test ${LIB}
